version: '3'

services:
  node:
    image: node:latest
    volumes:
      - .:/app
      - ./node_modules/:/app/node_modules
    working_dir: /app
    entrypoint: npm install && npm audit fix && npm run build

  vite:
    image: node:current-alpine
    depends_on: 
      node:
        condition: service_completed_successfully
    working_dir: /app
    ports:
      - 4173:4173
    volumes:
      - .:/app
    entrypoint: npm run dev -- --host 0.0.0.0
